TOP_DIR := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))
BIN_DIR = $(TOP_DIR)/bin
CONFIG_DIR = $(TOP_DIR)/config
MODULE_DIR = $(TOP_DIR)/modules
SOURCE_DIR = $(TOP_DIR)/src
TMP_DIR = $(TOP_DIR)/tmp

####################
#      include     #
####################

# /make/*.mkが全て展開される
-include $(SOURCE_DIR)/make/*.mk
-include $(MODULE_DIR)/*/Makefile

####################
#     targets      #
####################

# all
ALL_TARGETS +=
ALL_CLEAN_TARGETS +=
ALL_UPDATE_TARGETS +=

# dot
DOT_TARGETS +=
DOT_CLEAN_TARGETS +=

ALL_TARGETS += DOT_TARGETS
ALL_CLEAN_TARGETS += DOT_CLEAN_TARGETS

# starship
STARSHIP_TARGETS +=
STARSHIP_CLEAN_TARGETS +=

ALL_TARGETS += STARSHIP_TARGETS
ALL_CLEAN_TARGETS += STARSHIP_CLEAN_TARGETS

# fish
FISH_TARGETS +=
FISH_CLEAN_TARGETS +=
FISH_UPDATE_TARGETS +=

ALL_TARGETS += FISH_TARGETS
ALL_CLEAN_TARGETS += FISH_CLEAN_TARGETS
ALL_UPDATE_TARGETS += FISH_UPDATE_TARGETS

# tmux
TMUX_TARGETS +=
TMUX_CLEAN_TARGETS +=

ALL_TARGETS += TMUX_TARGETS
ALL_CLEAN_TARGETS += TMUX_CLEAN_TARGETS

# nvim
NVIM_TARGETS +=
NVIM_CLEAN_TARGETS +=

ALL_TARGETS += NVIM_TARGETS
ALL_CLEAN_TARGETS += NVIM_CLEAN_TARGETS

# code
CODE_TARGETS +=
CODE_CLEAN_TARGETS +=

ALL_TARGETS += CODE_TARGETS
ALL_CLEAN_TARGETS += CODE_CLEAN_TARGETS

# buttom
BOTTOM_TARGETS +=
BOTTOM_CLEAN_TARGETS +=

ALL_TARGETS += BOTTOM_TARGETS
ALL_CLEAN_TARGETS += BOTTOM_CLEAN_TARGETS

# aerospace
AEROSPACE_TARGETS +=
AEROSPACE_CLEAN_TARGETS +=

ALL_TARGETS += AEROSPACE_TARGETS
ALL_CLEAN_TARGETS += AEROSPACE_CLEAN_TARGETS

####################
#     commands     #
####################

.PHONY: all
all: $(ALL_TARGETS)

.PHONY: clean
clean: $(ALL_CLEAN_TARGETS)

.PHONY: update
update: $(ALL_UPDATE_TARGETS)
